name: Actions Workflow
on: [push]
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files before
        run: |
          pwd
          ls -lash
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
          # git clone git@github:$GITHUB_REPOSITORY
          # git checkout $GITHUB_SHA
      - name: Checkout
        uses: actions/checkout@v1
      - name: List files after
        run: |
          pwd
          ls -lash
      - name: Simple Javacript action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Pedro
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
